### ISSUE TITLE
Calling R script syntax

### ISSUE THREAD

**Issue by VJalili** [Genometric/mspc_validation#1]
Regarding:

https://github.com/Genometric/mscp_validation/blob/b36ccc50944b6d955eb7cfc512818feb891bcaf9/validation.py#L452-L457

Have you tried the following syntax? 

```python
subprocess.call (["/usr/bin/Rscript", "--vanilla", "/pathto/MyrScript.r"])
```

**Comment by fernandoPalluzzi** [comment]
No, but I can try it, thanks!
